# Generated by Django 5.0.6 on 2024-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_dicom/')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('imagen_indexada', models.ImageField(blank=True, null=True, upload_to='imagenes_indexadas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
