# Generated by Django 5.0.6 on 2024-06-24 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_alter_archivodicom_nombre_maquinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivodicom',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
