# Generated by Django 5.0.6 on 2024-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_archivodicom_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivodicom',
            name='bits_allocated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='bits_stored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='body_part_examined',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='image_orientation_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='image_position_patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='instance_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='manufacturer_model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='modality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='operators_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='performing_physician_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='protocol_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='series_instance_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='series_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='sop_instance_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='study_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='study_instance_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='study_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
