# Generated by Django 5.0.6 on 2024-05-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_archivodicom_delete_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodicom',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
