# Generated by Django 5.0.6 on 2024-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_maquinaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maquinaria',
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='genero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='nombre_estudio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivodicom',
            name='nombre_maquinaria',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
