# Generated by Django 5.0.6 on 2024-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_delete_maquinaria_archivodicom_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodicom',
            name='nombre_maquinaria',
            field=models.CharField(max_length=255),
        ),
    ]
