# Generated by Django 5.0.6 on 2024-06-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_archivodicom_nombre_maquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivodicom',
            name='nombre_maquinaria',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
